"use client";

import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import { useAuth } from "../src/auth/AuthContext";
import { addPayable, addTransaction, loadCashFlow } from "../src/services/cashflow";
import type { CashFlowData as Data, CashFlowMutation } from "../src/types";
type View = "dashboard"|"transactions"|"analytics"|"reports"|"accounts";

const emptyData: Data = { transactions:[], payables:[], accounts:[], categories:[] };

const peso = (value:number) => new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(Number(value)||0);
const dateLabel = (value:string) => value ? new Intl.DateTimeFormat("en-PH",{month:"short",day:"numeric",year:"numeric"}).format(new Date(`${value}T00:00:00`)) : "—";
const today = new Date().toISOString().slice(0,10);
const Icon = ({children}:{children:ReactNode}) => <span className="nav-icon" aria-hidden="true">{children}</span>;

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
  return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><div><p className="eyebrow">New record</p><h2>{title}</h2></div><button className="close-button" onClick={onClose} aria-label="Close">×</button></div>{children}</section></div>;
}

export default function Home(){
  const {profile,signOut}=useAuth();
  const [view,setView]=useState<View>("dashboard");
  const [data,setData]=useState<Data>(emptyData);
  const [connected,setConnected]=useState(false);
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [error,setError]=useState("");
  const [modal,setModal]=useState<"transaction"|"payable"|null>(null);
  const [notice,setNotice]=useState("");
  const [reportStart,setReportStart]=useState(`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,"0")}-01`);
  const [reportEnd,setReportEnd]=useState(today);

  const canWriteFinance=!!profile&&["Admin","Treasurer","Encoder"].includes(profile.role);
  const refresh=useCallback(async()=>{setLoading(true);setError("");try{setData(await loadCashFlow());setConnected(true)}catch(cause){setConnected(false);setError(cause instanceof Error?cause.message:"Unable to load financial data.")}finally{setLoading(false)}},[]);
  useEffect(()=>{queueMicrotask(()=>void refresh())},[refresh]);

  const totals=useMemo(()=>{
    const moneyIn=data.transactions.reduce((s,t)=>s+Number(t.moneyIn||0),0), moneyOut=data.transactions.reduce((s,t)=>s+Number(t.moneyOut||0),0);
    const balance=data.accounts.reduce((s,a)=>s+Number(a.currentBalance||0),0);
    const payables=data.payables.reduce((s,p)=>s+Number(p.balance||0),0);
    return {moneyIn,moneyOut,balance,net:moneyIn-moneyOut,payables};
  },[data]);
  const recent=[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);
  const expenseByCategory=useMemo(()=>Object.entries(data.transactions.reduce<Record<string,number>>((acc,t)=>{if(t.moneyOut){acc[t.category]=(acc[t.category]||0)+Number(t.moneyOut)}return acc},{})).sort((a,b)=>b[1]-a[1]),[data.transactions]);
  const monthly=useMemo(()=>{
    const now=new Date(); return Array.from({length:6},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-5+i,1);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;const rows=data.transactions.filter(t=>t.date.startsWith(key));return {label:d.toLocaleString("en",{month:"short"}),income:rows.reduce((s,t)=>s+Number(t.moneyIn||0),0),expense:rows.reduce((s,t)=>s+Number(t.moneyOut||0),0)}})
  },[data.transactions]);
  const maxMonth=Math.max(1,...monthly.flatMap(m=>[m.income,m.expense]));
  const reportRows=data.transactions.filter(t=>t.date>=reportStart&&t.date<=reportEnd);
  const reportIn=reportRows.reduce((s,t)=>s+Number(t.moneyIn||0),0), reportOut=reportRows.reduce((s,t)=>s+Number(t.moneyOut||0),0);

  const save=async(payload:CashFlowMutation)=>{setSaving(true);setNotice("Saving…");setError("");try{if(payload.action==="addTransaction")await addTransaction(payload.transaction,data);else await addPayable(payload.payable);await refresh();setNotice("Saved securely");setModal(null);setTimeout(()=>setNotice(""),2800)}catch(cause){const message=cause instanceof Error?cause.message:"Could not save this record.";setError(message);setNotice("Could not save. Review the message above.")}finally{setSaving(false)}};
  const exportCsv=()=>{const lines=[["Date","Type","Account","Category","Description","Money In","Money Out"],...reportRows.map(t=>[t.date,t.type,t.account,t.category,t.description,t.moneyIn,t.moneyOut])].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([lines],{type:"text/csv"}));a.download=`emmanuel-cash-flow-${reportStart}-to-${reportEnd}.csv`;a.click();URL.revokeObjectURL(a.href)};

  const headings:Record<View,[string,string]>={dashboard:["Good morning, Emmanuel.","Here’s how your cash is moving today."],transactions:["Transaction ledger","Every peso in and out, in one clean record."],analytics:["Cash flow analytics","See the patterns behind your financial activity."],reports:["Report generator","Create a clear, date-based cash flow statement."],accounts:["Accounts & payables","Monitor balances and what needs to be paid."]};
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">E</span><span>Emmanuel<br/><b>Cash Flow</b></span></div><nav aria-label="Main navigation">
      {([['dashboard','⌂','Dashboard'],['transactions','↕','Transactions'],['analytics','◫','Analytics'],['reports','▤','Reports'],['accounts','◎','Accounts']] as [View,string,string][]).map(([key,icon,label])=><button key={key} className={`nav-item ${view===key?'active':''}`} onClick={()=>setView(key)}><Icon>{icon}</Icon>{label}</button>)}
    </nav><div className="sidebar-foot"><div className="connection-state"><div className={`sync-dot ${connected?'':'pending'}`}/><span>{connected?"Database connected":"Connection pending"}</span></div><div className="signed-in-user"><b>{profile?.fullName||profile?.email}</b><small>{profile?.role}</small></div><button className="sign-out-button" onClick={()=>void signOut()}>Sign out</button></div></aside>

    <section className="workspace">
      <header className="topbar"><div><p className="eyebrow">{new Intl.DateTimeFormat("en",{weekday:"long",month:"long",day:"numeric"}).format(new Date())}</p><h1>{headings[view][0]}</h1><p className="subhead">{headings[view][1]}</p></div>{canWriteFinance&&<button className="primary-button" onClick={()=>setModal("transaction")}><span>＋</span>Add transaction</button>}</header>
      {notice&&<div className="toast" role="status">{notice}</div>}
      {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>void refresh()}>Try again</button></div>}

      {view==="dashboard"&&<><section className="metrics"><article className="metric-card featured"><div className="metric-label">Available balance <span>↗</span></div><strong>{peso(totals.balance)}</strong><p>Across {data.accounts.filter(a=>a.active!=="No").length} active accounts</p></article><article className="metric-card"><div className="metric-label">Money in <span className="badge positive">All time</span></div><strong>{peso(totals.moneyIn)}</strong><p className="positive-text">Income recorded</p></article><article className="metric-card"><div className="metric-label">Money out <span className="badge">All time</span></div><strong>{peso(totals.moneyOut)}</strong><p>Expenses recorded</p></article><article className="metric-card"><div className="metric-label">Payables <span>→</span></div><strong>{peso(totals.payables)}</strong><p>{data.payables.filter(p=>p.balance>0).length} open items</p></article></section>
        <section className="dashboard-grid"><article className="panel cashflow-panel"><div className="panel-head"><div><p className="eyebrow">Overview</p><h2>Cash flow</h2></div><span className="period-button">Last 6 months</span></div><div className="live-chart"><div className="grid-lines"><i/><i/><i/><i/></div>{monthly.map(m=><div className="month-group" key={m.label}><div className="month-bars"><i className="income-bar" style={{height:`${Math.max(m.income?5:1,m.income/maxMonth*100)}%`}}/><i className="expense-bar" style={{height:`${Math.max(m.expense?5:1,m.expense/maxMonth*100)}%`}}/></div><span>{m.label}</span></div>)}</div><div className="legend"><span><i/>Money in</span><span><i className="legend-out"/>Money out</span></div></article><article className="panel activity-panel"><div className="panel-head"><div><p className="eyebrow">Ledger</p><h2>Recent activity</h2></div><button className="text-button" onClick={()=>setView("transactions")}>View all →</button></div>{recent.length?<div className="activity-list">{recent.map(t=><div className="activity" key={t.id}><span className={`activity-mark ${t.type.toLowerCase()}`}>{t.type==="Income"?"↓":"↑"}</span><div><b>{t.description||t.category}</b><small>{dateLabel(t.date)} · {t.account}</small></div><strong className={t.type==="Income"?"income-text":""}>{t.type==="Income"?"+":"-"}{peso(t.moneyIn||t.moneyOut)}</strong></div>)}</div>:<div className="empty-state"><div className="empty-icon">↕</div><h3>Your ledger is ready</h3><p>{canWriteFinance?"Add your first income or expense. It will be stored securely in Supabase.":"No transactions have been recorded yet."}</p>{canWriteFinance&&<button className="secondary-button" onClick={()=>setModal("transaction")}>Add first transaction</button>}</div>}</article></section></>}

      {view==="transactions"&&<section className="panel table-panel"><div className="panel-head"><div><p className="eyebrow">{data.transactions.length} records</p><h2>All transactions</h2></div>{canWriteFinance&&<button className="secondary-button" onClick={()=>setModal("transaction")}>＋ New record</button>}</div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Description</th><th>Type</th><th>Account</th><th>Category</th><th className="num">Amount</th></tr></thead><tbody>{[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date)).map(t=><tr key={t.id}><td>{dateLabel(t.date)}</td><td><b>{t.description||"—"}</b><small>{t.reference||t.paymentMethod}</small></td><td><span className={`status ${t.type.toLowerCase()}`}>{t.type}</span></td><td>{t.account}</td><td>{t.category}</td><td className={`num ${t.type==="Income"?"income-text":""}`}>{t.type==="Income"?"+":"-"}{peso(t.moneyIn||t.moneyOut)}</td></tr>)}{!data.transactions.length&&<tr><td colSpan={6} className="blank-row">No transactions yet.{canWriteFinance?" Add one to begin your ledger.":""}</td></tr>}</tbody></table></div></section>}

      {view==="analytics"&&<section className="analytics-grid"><article className="panel"><div className="panel-head"><div><p className="eyebrow">Trend</p><h2>Inflow vs outflow</h2></div><span className={`net-pill ${totals.net<0?'negative':''}`}>{totals.net>=0?'Positive':'Negative'} cash flow</span></div><div className="big-number"><span>Net cash flow</span><strong>{peso(totals.net)}</strong></div><div className="analytics-bars">{monthly.map(m=><div key={m.label}><span>{m.label}</span><div className="track"><i style={{width:`${m.income/maxMonth*100}%`}}/><em style={{width:`${m.expense/maxMonth*100}%`}}/></div><small>{peso(m.income)} in · {peso(m.expense)} out</small></div>)}</div></article><article className="panel"><div className="panel-head"><div><p className="eyebrow">Expenses</p><h2>By category</h2></div></div><div className="category-list">{expenseByCategory.length?expenseByCategory.slice(0,8).map(([name,value])=><div key={name}><div><span>{name}</span><b>{peso(value)}</b></div><i><em style={{width:`${value/(expenseByCategory[0]?.[1]||1)*100}%`}}/></i></div>):<div className="empty-mini">Category insights will appear after expenses are recorded.</div>}</div></article></section>}

      {view==="reports"&&<section className="report-layout"><article className="panel report-controls no-print"><p className="eyebrow">Reporting period</p><h2>Build your statement</h2><label>Start date<input type="date" value={reportStart} onChange={e=>setReportStart(e.target.value)}/></label><label>End date<input type="date" value={reportEnd} onChange={e=>setReportEnd(e.target.value)}/></label><button className="secondary-button" onClick={()=>window.print()}>Print / Save PDF</button><button className="outline-button" onClick={exportCsv}>Export CSV</button></article><article className="panel report-sheet"><div className="report-brand"><span className="brand-mark">E</span><div><h2>Emmanuel Cash Flow</h2><p>Cash flow statement</p></div></div><div className="report-period">{dateLabel(reportStart)} — {dateLabel(reportEnd)}</div><div className="report-summary"><div><span>Money in</span><strong>{peso(reportIn)}</strong></div><div><span>Money out</span><strong>{peso(reportOut)}</strong></div><div className="report-net"><span>Net cash flow</span><strong>{peso(reportIn-reportOut)}</strong></div></div><h3>Transaction detail</h3><table><thead><tr><th>Date</th><th>Description</th><th>Category</th><th className="num">In</th><th className="num">Out</th></tr></thead><tbody>{reportRows.map(t=><tr key={t.id}><td>{dateLabel(t.date)}</td><td>{t.description}</td><td>{t.category}</td><td className="num">{t.moneyIn?peso(t.moneyIn):"—"}</td><td className="num">{t.moneyOut?peso(t.moneyOut):"—"}</td></tr>)}{!reportRows.length&&<tr><td colSpan={5} className="blank-row">No activity in this period.</td></tr>}</tbody></table><footer>Generated by Emmanuel Cash Flow · Source: Emmanuel database</footer></article></section>}

      {view==="accounts"&&<><section className="account-cards">{data.accounts.map(a=><article className="account-card" key={a.name}><span>{a.type}</span><h3>{a.name}</h3><strong>{peso(a.currentBalance)}</strong><div><small>Money in <b>{peso(a.moneyIn)}</b></small><small>Money out <b>{peso(a.moneyOut)}</b></small></div></article>)}{!data.accounts.length&&!loading&&<div className="empty-mini">No accounts are available.</div>}</section><section className="panel table-panel payables-panel"><div className="panel-head"><div><p className="eyebrow">Commitments</p><h2>Payables</h2></div>{canWriteFinance&&<button className="secondary-button" onClick={()=>setModal("payable")}>＋ Add payable</button>}</div><div className="table-wrap"><table><thead><tr><th>Due</th><th>Vendor / Payee</th><th>Category</th><th>Status</th><th className="num">Balance</th></tr></thead><tbody>{data.payables.map(p=><tr key={p.id}><td>{dateLabel(p.dueDate)}</td><td><b>{p.vendor}</b></td><td>{p.category}</td><td><span className={`status ${p.status.toLowerCase().replaceAll(' ','-')}`}>{p.status}</span></td><td className="num">{peso(p.balance)}</td></tr>)}{!data.payables.length&&<tr><td colSpan={5} className="blank-row">No payables recorded.</td></tr>}</tbody></table></div></section></>}
    </section>

    {modal==="transaction"&&canWriteFinance&&<Modal title="Add transaction" onClose={()=>setModal(null)}><TransactionForm data={data} saving={saving} onSubmit={save}/></Modal>}
    {modal==="payable"&&canWriteFinance&&<Modal title="Add payable" onClose={()=>setModal(null)}><PayableForm data={data} saving={saving} onSubmit={save}/></Modal>}
    {loading&&<div className="loading-line"/>}
  </main>
}

function TransactionForm({data,saving,onSubmit}:{data:Data;saving:boolean;onSubmit:(p:CashFlowMutation)=>Promise<void>}){
 const [type,setType]=useState<"Income"|"Expense">("Income"); const cats=data.categories.filter(c=>c.type===type);
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),amount=Number(f.get("amount"));void onSubmit({action:"addTransaction",transaction:{id:crypto.randomUUID(),date:String(f.get("date")||""),type,account:String(f.get("account")||""),category:String(f.get("category")||""),description:String(f.get("description")||""),moneyIn:type==="Income"?amount:0,moneyOut:type==="Expense"?amount:0,paymentMethod:String(f.get("paymentMethod")||""),reference:String(f.get("reference")||""),notes:String(f.get("notes")||""),createdAt:new Date().toISOString()}})};
 return <form className="record-form" onSubmit={submit}><div className="segmented"><button type="button" className={type==="Income"?"selected":""} onClick={()=>setType("Income")}>Money in</button><button type="button" className={type==="Expense"?"selected expense":""} onClick={()=>setType("Expense")}>Money out</button></div><div className="form-grid"><label>Date<input name="date" type="date" defaultValue={today} required/></label><label>Amount (PHP)<input name="amount" type="number" min="0.01" step="0.01" placeholder="0.00" required/></label><label>Account<select name="account" required>{data.accounts.map(a=><option key={a.id} value={a.name}>{a.name}</option>)}</select></label><label>Category<select name="category" required>{cats.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></label><label className="full">Description<input name="description" placeholder="What was this for?" required/></label><label>Payment method<select name="paymentMethod"><option>Cash</option><option>Bank Transfer</option><option>Check</option><option>Card</option><option>Online</option><option>Other</option></select></label><label>Reference<input name="reference" placeholder="Receipt or reference no."/></label><label className="full">Notes<textarea name="notes" rows={3} placeholder="Optional notes"/></label></div><button className="primary-button form-submit" disabled={saving||!data.accounts.length||!cats.length}>{saving?"Saving…":"Save transaction"}</button></form>
}

function PayableForm({data,saving,onSubmit}:{data:Data;saving:boolean;onSubmit:(p:CashFlowMutation)=>Promise<void>}){
 const expenseCategories=data.categories.filter(c=>c.type==="Expense");
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),amount=Number(f.get("amount")),categoryId=String(f.get("categoryId")||""),category=data.categories.find(c=>c.id===categoryId);if(!category)return;void onSubmit({action:"addPayable",payable:{id:crypto.randomUUID(),vendor:String(f.get("vendor")||""),dueDate:String(f.get("dueDate")||""),category:category.name,categoryId,amount,amountPaid:0,balance:amount,status:"Unpaid",notes:String(f.get("notes")||""),createdAt:new Date().toISOString()}})};
 return <form className="record-form" onSubmit={submit}><div className="form-grid"><label className="full">Vendor / Payee<input name="vendor" placeholder="Who needs to be paid?" required/></label><label>Due date<input name="dueDate" type="date" defaultValue={today} required/></label><label>Amount (PHP)<input name="amount" type="number" min="0.01" step="0.01" required/></label><label className="full">Category<select name="categoryId" required>{expenseCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="full">Notes<textarea name="notes" rows={3}/></label></div><button className="primary-button form-submit" disabled={saving||!expenseCategories.length}>{saving?"Saving…":"Save payable"}</button></form>
}
