import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "../auth/AuthContext";
import { createChurchDraft, loadPlatformOverview } from "../services/platformAdministration";
import type { PlatformOverview } from "../types";
import { ChurchWorkspaceSwitcher } from "./tenancy/ChurchWorkspaceSwitcher";
import { ChurchBrand } from "./ui/ChurchBrand";
import { EmptyState } from "./ui/EmptyState";
import { LoadingSkeleton } from "./ui/LoadingSkeleton";
import { UserProfileIndicator } from "./ui/UserProfileIndicator";

const statusLabel=(status:string)=>status.charAt(0).toUpperCase()+status.slice(1);
const platformOwnerRole="Platform Owner" as const;

export function PlatformAdministrationView(){
  const {profile,signOut}=useAuth();
  const [overview,setOverview]=useState<PlatformOverview|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[formOpen,setFormOpen]=useState(false),[saving,setSaving]=useState(false);
  const refresh=useCallback(async()=>{setLoading(true);setError("");try{setOverview(await loadPlatformOverview());}catch(cause){setError(cause instanceof Error?cause.message:"Unable to load platform administration.");}finally{setLoading(false);}},[]);
  useEffect(()=>{queueMicrotask(()=>void refresh());},[refresh]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();const form=new FormData(event.currentTarget);setSaving(true);setError("");
    try{await createChurchDraft({name:String(form.get("name")||""),slug:String(form.get("slug")||""),address:String(form.get("address")||""),timezone:String(form.get("timezone")||"Asia/Manila"),currency:String(form.get("currency")||"PHP")});setFormOpen(false);setNotice("Inactive church draft created. No financial access was granted.");await refresh();}
    catch(cause){setError(cause instanceof Error?cause.message:"Unable to create church draft.");}
    finally{setSaving(false);}
  };
  return <main className="platform-shell">
    <aside className="platform-sidebar"><ChurchBrand inverse/><div className="platform-owner-badge">Platform Owner</div><nav><button className="nav-item active">Platform Overview</button><button className="nav-item" onClick={()=>document.getElementById("platform-churches")?.scrollIntoView({behavior:"smooth"})}>Churches</button></nav><div className="platform-sidebar-bottom"><ChurchWorkspaceSwitcher/>{profile&&<UserProfileIndicator name={profile.fullName} email={profile.email} role={platformOwnerRole}/>}<button className="nav-item logout-nav" onClick={()=>void signOut()}>Logout</button></div></aside>
    <section className="platform-workspace"><header className="topbar"><div><p className="eyebrow">Faithful Steward platform</p><h1>Platform Administration</h1><p className="subhead">Manage tenant onboarding without entering church financial workspaces.</p></div><div className="topbar-actions"><ChurchWorkspaceSwitcher compact/><button className="primary-button" onClick={()=>setFormOpen(true)}>＋ New Church Draft</button></div></header>
      {notice&&<div className="form-success" role="status">{notice}</div>}{error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>void refresh()}>Try again</button></div>}
      {loading?<section className="panel"><LoadingSkeleton rows={5} label="Loading platform overview"/></section>:overview&&<><section className="leadership-metrics platform-metrics"><article className="metric-card featured"><small>Total churches</small><strong>{overview.churches.length}</strong><p>{overview.churches.filter(church=>church.status==="active").length} active</p></article><article className="metric-card"><small>Platform users</small><strong>{overview.totalUsers}</strong><p>Identity profiles only</p></article><article className="metric-card"><small>Church memberships</small><strong>{overview.totalMemberships}</strong><p>Access remains tenant-specific</p></article></section><section id="platform-churches" className="panel table-panel"><div className="panel-head"><div><p className="eyebrow">Tenant directory</p><h2>Churches</h2></div><span className="period-button">No financial access implied</span></div><div className="table-wrap responsive-table"><table><thead><tr><th>Church</th><th>Status</th><th>Workspace</th><th>Region</th><th>Members</th><th>Church Admins</th></tr></thead><tbody>{overview.churches.map(church=><tr key={church.id}><td data-label="Church"><b>{church.name}</b><small>{church.address||"No address added"}</small></td><td data-label="Status"><span className={`status ${church.status==="active"?"paid":"unpaid"}`}>{statusLabel(church.status)}</span></td><td data-label="Workspace"><code>{church.slug}</code></td><td data-label="Region">{church.timezone}<small>{church.currency}</small></td><td data-label="Members">{church.activeMemberships} active / {church.totalMemberships}</td><td data-label="Church Admins">{church.activeAdmins}</td></tr>)}{!overview.churches.length&&<tr><td colSpan={6}><EmptyState compact title="No church tenants" description="Create an inactive onboarding draft when a church is ready to begin setup."/></td></tr>}</tbody></table></div></section><section className="panel platform-security-note"><h2>Security boundary</h2><p>Platform Owner status does not grant access to any church’s finances. Financial access still requires an explicit active church membership and remains enforced by Supabase RLS.</p></section></>}
    </section>
    {formOpen&&<div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)setFormOpen(false);}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="church-draft-title"><div className="modal-head"><div><p className="eyebrow">Tenant onboarding</p><h2 id="church-draft-title">New church draft</h2></div><button className="close-button" onClick={()=>setFormOpen(false)} disabled={saving}>×</button></div><form className="record-form" onSubmit={submit}><div className="form-grid"><label className="full">Church name<input name="name" minLength={2} maxLength={200} required/></label><label className="full">Workspace slug<input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="grace-community-church" required/></label><label className="full">Address<input name="address"/></label><label>Timezone<input name="timezone" defaultValue="Asia/Manila" required/></label><label>Currency<input name="currency" defaultValue="PHP" pattern="[A-Za-z]{3}" maxLength={3} required/></label></div><p className="audit-note">This creates an inactive tenant draft only. It grants no membership or financial access and cannot be selected as a live workspace yet.</p><button className="primary-button form-submit" disabled={saving}>{saving?"Creating draft…":"Create inactive draft"}</button></form></section></div>}
  </main>;
}
