import { FormEvent, useCallback, useEffect, useState } from "react";
import { loadProjects, saveProject } from "../services/projects";
import type { Project, ProjectInput } from "../types";

const peso=(value:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(value||0);
const dateLabel=(value:string|null)=>value?new Intl.DateTimeFormat("en-PH",{month:"short",day:"numeric",year:"numeric"}).format(new Date(`${value}T00:00:00`)):"Not set";
const statuses:ProjectInput["status"][]=["Planned","Active","On Hold","Completed","Cancelled"];

function ProjectProgress({project}:{project:Project}) {
  const progress=project.funding;
  if(progress.goalAmount===null||progress.currentAmountRaised===null||progress.progressPercentage===null)return null;
  return <div className="project-progress"><div><span>{peso(progress.currentAmountRaised)} raised</span><b>{Math.min(100,Math.max(0,progress.progressPercentage))}%</b></div><i><em style={{width:`${Math.min(100,Math.max(0,progress.progressPercentage))}%`}}/></i><small>Goal {peso(progress.goalAmount)} · Target {dateLabel(progress.targetDate)}</small></div>;
}

function ProjectForm({project,saving,onCancel,onSubmit}:{project:Project|null;saving:boolean;onCancel:()=>void;onSubmit:(input:ProjectInput)=>Promise<void>}) {
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);void onSubmit({id:project?.id,name:String(form.get("name")||""),description:String(form.get("description")||""),budget:Number(form.get("budget")),startDate:String(form.get("startDate")||"")||null,endDate:String(form.get("endDate")||"")||null,status:String(form.get("status")||"Planned") as ProjectInput["status"]});};
  return <div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target&&!saving)onCancel();}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="project-form-title"><div className="modal-head"><div><p className="eyebrow">Project management</p><h2 id="project-form-title">{project?"Edit project":"Add project"}</h2></div><button className="close-button" disabled={saving} onClick={onCancel} aria-label="Close">×</button></div><form className="record-form" onSubmit={submit}><div className="form-grid"><label className="full">Project name<input name="name" defaultValue={project?.name||""} required/></label><label>Budget (PHP)<input name="budget" type="number" min="0" step="0.01" defaultValue={project?.budget||0} required/></label><label>Status<select name="status" defaultValue={project?.status||"Planned"}>{statuses.map(status=><option key={status}>{status}</option>)}</select></label><label>Start date<input name="startDate" type="date" defaultValue={project?.startDate||""}/></label><label>Target / end date<input name="endDate" type="date" defaultValue={project?.endDate||""}/></label><label className="full">Description<textarea name="description" rows={4} defaultValue={project?.description||""}/></label></div><p className="form-help">Funding goal, amount raised, percentage progress, and a dedicated target date can be added to this project card without changing its layout.</p><button className="primary-button form-submit" disabled={saving}>{saving?"Saving…":project?"Save project changes":"Create project"}</button></form></section></div>;
}

export function ProjectsView({churchId,canManage}:{churchId:string;canManage:boolean}) {
  const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState<Project|null>(null);
  const [formOpen,setFormOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  const [error,setError]=useState(""),[notice,setNotice]=useState("");
  const refresh=useCallback(async()=>{setLoading(true);setError("");try{setProjects(await loadProjects(churchId));}catch(cause){setError(cause instanceof Error?cause.message:"Unable to load projects.");}finally{setLoading(false);}},[churchId]);
  useEffect(()=>{queueMicrotask(()=>void refresh());},[refresh]);
  const open=(project:Project|null)=>{setSelected(project);setFormOpen(true);setError("");};
  const submit=async(input:ProjectInput)=>{setSaving(true);setError("");try{await saveProject(churchId,input);setFormOpen(false);setSelected(null);setNotice("Project saved securely.");await refresh();window.setTimeout(()=>setNotice(""),2500);}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save the project.");}finally{setSaving(false);}};
  return <section className="projects-view"><div className="panel projects-heading"><div className="panel-head"><div><p className="eyebrow">Church initiatives</p><h2>Projects</h2></div>{canManage&&<button className="primary-button" onClick={()=>open(null)}>＋ Add Project</button>}</div><p className="section-copy">Plan and track church projects while keeping the structure ready for future fundraising progress.</p></div>{notice&&<div className="form-success" role="status">{notice}</div>}{error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>void refresh()}>Try again</button></div>}{loading?<div className="panel empty-state" role="status"><div className="empty-icon">◷</div><h3>Loading projects</h3><p>Retrieving the current project list…</p></div>:projects.length?<div className="project-grid">{projects.map(project=><article className="project-card" key={project.id}><div className="project-card-head"><span className={`status project-${project.status.toLowerCase().replaceAll(" ","-")}`}>{project.status}</span><span>{dateLabel(project.endDate)}</span></div><h3>{project.name}</h3><p>{project.description||"No project description yet."}</p><div className="project-budget"><span>Budget</span><b>{peso(project.budget)}</b></div><ProjectProgress project={project}/>{canManage&&<button className="outline-button" onClick={()=>open(project)}>Manage project</button>}</article>)}</div>:<div className="panel empty-state"><div className="empty-icon">◇</div><h3>No projects yet</h3><p>{canManage?"Add the first church project when planning begins.":"Projects will appear here when they are created."}</p></div>}{formOpen&&canManage&&<ProjectForm project={selected} saving={saving} onCancel={()=>{setFormOpen(false);setSelected(null);}} onSubmit={submit}/>}</section>;
}
