import { useCallback, useEffect, useMemo, useState } from "react";
import { AccessRequestsView } from "./AccessRequestsView";
import { loadManagedUsers, updateUserAccess } from "../services/users";
import type { ManagedUser, Role } from "../types";

type Draft={roleId:string;isActive:boolean};

export function UsersView({currentUserId}:{currentUserId:string}) {
  const [tab,setTab]=useState<"users"|"requests">("users"),[users,setUsers]=useState<ManagedUser[]>([]),[roles,setRoles]=useState<Role[]>([]);
  const [drafts,setDrafts]=useState<Record<string,Draft>>({}),[loading,setLoading]=useState(true),[savingId,setSavingId]=useState("");
  const [error,setError]=useState(""),[notice,setNotice]=useState("");
  const refresh=useCallback(async()=>{setLoading(true);setError("");try{const next=await loadManagedUsers();setUsers(next.users);setRoles(next.roles);setDrafts(Object.fromEntries(next.users.map(user=>[user.id,{roleId:user.roleId,isActive:user.isActive}])));}catch(cause){setError(cause instanceof Error?cause.message:"Unable to load users.");}finally{setLoading(false);}},[]);
  useEffect(()=>{queueMicrotask(()=>void refresh());},[refresh]);
  const changed=useMemo(()=>new Set(users.filter(user=>{const draft=drafts[user.id];return draft&&(draft.roleId!==user.roleId||draft.isActive!==user.isActive);}).map(user=>user.id)),[drafts,users]);
  const save=async(user:ManagedUser)=>{const draft=drafts[user.id];if(!draft)return;setSavingId(user.id);setError("");setNotice("");try{await updateUserAccess({userId:user.id,...draft});setNotice(`${user.fullName||user.email} access updated.`);await refresh();window.setTimeout(()=>setNotice(""),2500);}catch(cause){setError(cause instanceof Error?cause.message:"Unable to update this user.");}finally{setSavingId("");}};
  return <section className="users-module"><div className="module-tabs" aria-label="User administration"><button className={tab==="users"?"active":""} onClick={()=>setTab("users")}>Users</button><button className={tab==="requests"?"active":""} onClick={()=>setTab("requests")}>Access Requests</button></div>{tab==="requests"?<AccessRequestsView/>:<section className="panel table-panel users-panel"><div className="panel-head"><div><p className="eyebrow">Admin controls</p><h2>User access</h2></div><span className="period-button">{users.length} users</span></div><p className="audit-note">Role and status changes are written to the immutable audit log. Users are never deleted so financial history remains connected.</p>{notice&&<div className="form-success access-message" role="status">{notice}</div>}{error&&<div className="error-banner access-message" role="alert"><span>{error}</span><button onClick={()=>void refresh()}>Try again</button></div>}{loading?<div className="empty-state" role="status"><div className="empty-icon">◷</div><h3>Loading users</h3><p>Retrieving secured user profiles and roles…</p></div>:<div className="table-wrap users-table"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map(user=>{const self=user.id===currentUserId,draft=drafts[user.id]||{roleId:user.roleId,isActive:user.isActive};return <tr key={user.id}><td><b>{user.fullName||"Unnamed user"}</b>{self&&<small>Current Admin</small>}</td><td>{user.email}</td><td><select aria-label={`Role for ${user.fullName||user.email}`} value={draft.roleId} disabled={self||!!savingId} onChange={event=>setDrafts(current=>({...current,[user.id]:{...draft,roleId:event.target.value}}))}>{roles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select></td><td><select aria-label={`Status for ${user.fullName||user.email}`} value={draft.isActive?"active":"inactive"} disabled={self||!!savingId} onChange={event=>setDrafts(current=>({...current,[user.id]:{...draft,isActive:event.target.value==="active"}}))}><option value="active">Active</option><option value="inactive">Inactive</option></select></td><td>{self?<span className="self-protection">Protected</span>:<button className="table-action" disabled={!changed.has(user.id)||!!savingId} onClick={()=>void save(user)}>{savingId===user.id?"Saving…":"Save changes"}</button>}</td></tr>;})}{!users.length&&<tr><td colSpan={5} className="blank-row">No user profiles are available.</td></tr>}</tbody></table></div>}</section>}</section>;
}
