export type BackupExportType = "transactions" | "money-in" | "money-out" | "transfers" | "payables" | "payable-payments" | "users" | "projects" | "audit-logs";

export type BackupExportScope = {
  allRecords: boolean;
  dateFrom: string;
  dateTo: string;
};

export type BackupDataset = {
  type: BackupExportType;
  title: string;
  headers: string[];
  rows: (string | number | boolean | null)[][];
};

export type BackupExportMetadata = {
  exportId: string;
  organization: string;
  generatedAt: string;
  generatedBy: string;
  scopeLabel: string;
};

const csvCell = (value: string | number | boolean | null) => {
  const text = value === null ? "" : String(value);
  return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
};

export function createExportId(now = new Date(), randomValue?: string) {
  const date = now.toISOString().slice(0, 10).replaceAll("-", "");
  const random = (randomValue || globalThis.crypto?.randomUUID?.() || `${now.getTime()}`)
    .replaceAll("-", "").slice(0, 8).toUpperCase();
  return `EXP-${date}-${random}`;
}

export function scopeLabel(scope: BackupExportScope) {
  return scope.allRecords ? "All available records" : `${scope.dateFrom} to ${scope.dateTo}`;
}

export function buildBackupCsv(dataset: BackupDataset, metadata: BackupExportMetadata) {
  const metadataRows = [
    ["Organization", metadata.organization],
    ["Report", dataset.title],
    ["Export ID", metadata.exportId],
    ["Scope", metadata.scopeLabel],
    ["Generated at", metadata.generatedAt],
    ["Generated by", metadata.generatedBy],
    ["Record count", dataset.rows.length],
  ];
  const lines = [
    ...metadataRows.map(row => row.map(csvCell).join(",")),
    "",
    dataset.headers.map(csvCell).join(","),
    ...dataset.rows.map(row => row.map(csvCell).join(",")),
  ];
  return `\uFEFF${lines.join("\r\n")}`;
}

export function downloadBackupCsv(dataset: BackupDataset, metadata: BackupExportMetadata) {
  const blob = new Blob([buildBackupCsv(dataset, metadata)], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${dataset.type}-${metadata.exportId}.csv`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}
